image:
  repository: 130219922021/complete-devops-project
  pullPolicy: IfNotPresent
  tag: 5b01d02
service:
  type: ClusterIP
  port: 8080
ingress: 
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: true
  minReplicas: 3  
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
resources:
  limits:
    cpu: 1000 m
    memory: 1024Mi
  requests:
    cpu: 500m 
    memory: 512Mi
nodeSelector: {}  
tolerations: []
affinity: {}

