image:
  repository: 130219922021/complete-devops-project
  pullPolicy: IfNotPresent
  tag: fcb6921
service:
  type: ClusterIP
  port: 8080
ingress: 
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false
  
