image:
  repository: 130219922021/complete-devops-project
  pullPolicy: IfNotPresent
  tag: d620257
service:
  type: ClusterIP
  port: 8080
ingress: 
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: true
  minReplicas: 3  
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60

